version: "3"

services:
  workspace:
    build:
      context: ./workspace/docker
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /ecpg-playground
    tty: true
    stdin_open: true
  db:
    build:
      context: ./db/docker
      dockerfile: Dockerfile
    # restart: always
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 15432:5432
    volumes:
      - type: volume
        source: ecpg_playground_volume
        target: "/var/lib/postgresql/data"

volumes:
  ecpg_playground_volume:

#secrets:
#  db_password:
#    file: ./db/password.txt
